SAP/styleguides

clean-abap/CleanABAP.md

remove double spaces
according to rule https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#condense-your-code

whitespace fixes

---

clean-abap/CleanABAP.md

* formatting
* align parameters
* fix syntax error
suggest squashing when merging

minor fixes

---

clean-abap/CleanABAP.md

removed lparen, looks like a syntax error?

removed lparen, looks like a syntax error?

---

clean-abap/CleanABAP.md

Proposal for correction to fix the Issue #19 
Wrong Link in section "if your global class is create private leave the constructor public"

Exchanged internal link to help.sap.com

---

clean-abap/CleanABAP.md

Chapter "Split methods instead of adding OPTIONAL parameters" describes an anti-pattern with optional parameters without using OPTIONAL.

Missing "OPTIONAL"

---

clean-abap/CleanABAP.md

In response to https://github.com/SAP/styleguides/issues/3.

Added section "How to Check Automatically"

---

clean-abap/CleanABAP.md

Added some further notes on performance. Feel free to discuss/disagree/edit/ignore, I'm happy to change things too if there are any suggestions.

Performance notes

---

clean-abap/sub-sections/Exceptions.md

... to avoid the misunderstanding in https://github.com/SAP/styleguides/issues/16#issuecomment-492831365 (https://github.com/SAP/styleguides/issues/16)

Clarify the behavior of `cx_static_check`

---

clean-abap/CleanABAP.md

Please, consider adding this advice.

tables: single read without checking presence

---

clean-abap/CleanABAP.md

BTW: I am not sure if it is anti-pattern or not because I consider it
an anti-pattern as it is hard to get for me.

method: drop anti-pattern from a recommendation

---

clean-abap/CleanABAP.md

Added some steps on how you can add clean code to a legacy project. After all, this will be the 90% case of all readers - having to add these suggestions to an existing code base.

Added advice on refactoring

---

clean-abap/CleanABAP.md

Fixed some minor typos in CleanABAP.md

---

clean-abap/CleanABAP.md

Added a link, a menu navigation and corrected some minor typos.

Minor adjustments to CleanABAP.md

---

clean-abap/CleanABAP.md

I believe you meant cx_static_check instead of cx_dynamic_check. Seems to make more sense in that chapter.

Fixed INHERITING FROM class

---

clean-abap/sub-sections/FunctionGroupsVsClasses.md

Changed "too" to "either" in accordance to https://www.talkenglish.com/grammar-a2z/lessondetails.aspx?ALID=4391

Minor wording change to FunctionGroupsVsClasses.md

---

clean-abap/CleanABAP.md

Added subsection "Omit the self-reference me when calling an instance method"

Update CleanABAP.md with subsection on omit of the self-reference me->

---

clean-abap/CleanABAP.md

Addressing https://github.com/SAP/styleguides/issues/72

Add section Prefer IS NOT to NOT IS

---

clean-abap/sub-sections/ModernABAPLanguageElements.md

Fixed inconsistent header level formatting

Formatting fix for ModernABAPLanguageElements.md

---

clean-abap/CleanABAP.md

Added a subsection on making messages easy to find

Added a subsection for messages

---

clean-abap/CleanABAP.md

exchanged the title to clearly make it optional to use

CL_ABAP_TESTDOUBLE title

---

clean-abap/CleanABAP.md

- add test relations for system tests incl. example
- remove the "accidental delivered" statement

Put tests in local classes

---

clean-abap/CleanABAP.md

- factory methods -> creation methods
- constructor methods -> creation methods
- missing anti-pattern label
- align method call parameters at line start is not an anti-pattern

Minor changes

---

clean-abap/CleanABAP.md

In response to https://github.com/SAP/styleguides/issues/46. Making the intention of the section clearer. Worked our SAP-internal story into general advice.

Rework section on local classes

---

clean-abap/CleanABAP.md

Hi, 
I think abaplint deserves a mention in the automatic checking section. I've tried it on our codebase and can attest that it handles 99% of modern abap correctly (and bugs get resolved very fast). New rules are still being added and can be contributed by the community as well.
In an attempt to make it more user-friendly, I made a [repository](https://github.com/FreHu/abaplint-clean-code) containing some rule documentation as well as a Clean ABAP aligned config (link can be found in the abaplint readme).
Feel free to propose any changes to the wording.

Mention abaplint in 'How to check automatically'

---

clean-abap/CleanABAP.md

the automatic TOC  creation detected an inconsistency in the TOC, now fixed

fix TOC entry

---

clean-abap/CleanABAP.md

Added new sub-section "Prefer pragmas to pseudo comments" to the "Comments" section.

New section: Prefer pragmas to pseudo comments

---

clean-abap/CleanABAP.md

Until https://github.com/SAP/styleguides/issues/115 has been clarified.

Add disclaimer about discussion REF TO vs FIELD-SYMBOL

---

clean-abap/sub-sections/ModernABAPLanguageElements.md

ModernABAPLanguageElements typos

---

clean-abap/CleanABAP.md

Added an exception type criteria

Do one thing only - added criteria

---

clean-abap/CleanABAP.md

Syntax fix "ani-pattern"

---

clean-abap/CleanABAP.md

ENDMETHOD. instead of ENDMETHOD:

Syntax fix: "ENDMETHOD:"

---

clean-abap/CleanABAP.md

Fixed broken link "throws one type of exception"

Fixed broken link

---

clean-abap/CleanABAP.md

Catching up the discussion from #134

Headline "Test interfaces, not classes" is misleading

---

clean-abap/CleanABAP.md

Added details on alternative approach.

Avoid CHECK in other positions

---

clean-abap/CleanABAP.md

The IF from line 1170 was closed with ENDTRY, on line 1172. I believe this should have been a mistake, fixed to closing with ENDIF.

Updated wrong closing code

---

clean-abap/CleanABAP.md
clean-abap/CleanABAP_zh.md

Some months back we came to the conclusion that a Chinese translation would help a lot of ABAPers, We initiated this translation through SAP's translation partners. Then came Corona and I lost track of some issues, including this one. :-( Anyway, better late than never, so here we go! 🍾  
This PR reflects a Chinese translation of Clean ABAP as of Nov 14, 2020. Unfortunately, the translation tools don't provide translators with the full Markdown, and don't offer a means to migrate the document-intenal links alongside.

Add Chinese translation

---

clean-abap/CleanABAP.md

To close https://github.com/SAP/styleguides/issues/104

Add the detail that Clean ABAP is now reference guide for S/4

---

clean-abap/CleanABAP_fr.md
clean-abap/CleanABAP_zh.md

As the discussion in #152, I created a script to fix broken links.
#160 has some issues, so I closed it and created this one.

fix broken links for Chinese translation 

---

clean-abap/CleanABAP_fr.md

fix broken links for Français

---

clean-abap/CleanABAP.md

Correct a typo

---

README.md

main README: fix broken link

---

clean-abap/CleanABAP.md

Think it's time to give code pal a more prominent mention in this guide. That project has grown considerably over the past months. Looks like it can make a valuable contribution to automatic style checks.

Link to Code Pal

---

abap-code-review/README.md

make online AsciiDoc more prominent

---

.reuse/dep5
LICENSES/CC-BY-3.0.txt
NOTICE
README.md

In line with SAP OSPO requirements, this PR removes the NOTICE file and adds support for the REUSE Tool.
Note: Please register the repository with the REUSE Tool to complete the integration (see #227)
Fixes #207 
Fixes #225
Fixes #228

chore: Add REUSE tool support

---

.vscode/settings.json
clean-abap/CleanABAP.md
clean-abap/CleanABAP_de.md
clean-abap/CleanABAP_es.md
clean-abap/CleanABAP_fr.md
clean-abap/CleanABAP_ja.md
clean-abap/CleanABAP_zh.md

Added a new .md file that contains the Spanish translation and updated links to the other language files.

Added Spanish translation

---

clean-abap/CleanABAP.md
clean-abap/CleanABAP_de.md
clean-abap/CleanABAP_es.md
clean-abap/CleanABAP_fr.md
clean-abap/CleanABAP_ja.md
clean-abap/CleanABAP_zh.md

The link to DSAG's recommendations was broken, I guess they did something on their CMS.

Fix broken external link

---

clean-abap/CleanABAP.md

Ref https://github.com/SAP/styleguides/issues/250

Avoid obscuring built-in functions

---

clean-abap/CleanABAP.md

For https://github.com/SAP/styleguides/issues/188

Add signature to clarify sub-classed exception

---

abap-code-review/src/tools.adoc
asciidoc-link-check-config.json
package-lock.json
package.json

fixes error in https://github.com/SAP/styleguides/pull/274
+ update dependencies to latest
+ node 16 package.json format

code review guide: fix link to git handbook

---

clean-abap/CleanABAP.md

Improves unclear example, see issue #268

Improve explanation of chaining example

---

.github/workflows/build.yml

* remove pdf upload
* switch to v3 for node16

fix github actions

---

abap-code-review/ABAPCodeReview.md
clean-abap/CleanABAP.md
clean-abap/sub-sections/Enumerations.md
mlc_config.json
package.json

xargs instead of exec
see https://github.com/tcort/markdown-link-check

fix markdown-link-check

---

.github/labeler.yml
.github/workflows/labeler.yml

Adds a GitHub Action that will automatically label new pull requests depending on the files changed: Requests that change anything within the clean-abap folder will be labeled https://github.com/SAP/styleguides/labels/clean-abap, while requests that change anything within the abap-code-review folder will be labeled https://github.com/SAP/styleguides/labels/abap-code-review.

Automatic pull request labeling

---

clean-abap/CleanABAP_de.md

This PR contains minor adjustment to correct the translation issue indicated in [issue 321](https://github.com/SAP/styleguides/issues/321).

German Translation: Typo

---

package-lock.json
package.json

Fix top-level npm package name for disambiguation. (Left-over from abap-code-review-guide refactoring)

Fix npm package name

---

clean-abap/CleanABAP.md

I have added a few lines and sample coding to show how to use the ABAP authorization double.

Add abap authorization double to "Exploit the test tools"

---

clean-abap/CleanABAP.md

As suggested by @larshp in #288, here's the first idea of that section as a pull request.

Don't access types through instance variables

---

clean-abap/CleanABAP.md
clean-abap/CleanABAP_de.md
clean-abap/CleanABAP_fr.md

Correct message display shortcut key
